import React, { useState, useEffect } from 'react';
import { getCompanies, generateFinalReport } from '../services/api';
import { FileText, Download, Brain, Building2, Calendar, CheckCircle, Loader, Zap } from 'lucide-react';

function GenerateReport() {
  const [companies, setCompanies] = useState([]);
  const [selectedCompany, setSelectedCompany] = useState('');
  const [reportType, setReportType] = useState('comprehensive');
  const [period, setPeriod] = useState('Q4 2024');
  const [includeAI, setIncludeAI] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [report, setReport] = useState(null);
  const [error, setError] = useState(null);

  // Render AI content with professional formatting - simple and clean
  const renderAiContent = (content) => {
    if (!content) return null;

    // Clean up markdown and format nicely
    const formatContent = (text) => {
      return text
        // Remove markdown headers but keep text
        .replace(/^#{1,6}\s*/gm, '')
        // Convert **bold** to styled spans
        .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
        // Convert *italic* to styled spans
        .replace(/\*([^*]+)\*/g, '<em>$1</em>')
        // Clean up extra dashes
        .replace(/^--\s*/gm, '')
        // Clean up multiple newlines
        .replace(/\n{3,}/g, '\n\n');
    };

    const formattedContent = formatContent(content);

    return (
      <div
        style={{
          fontSize: '14px',
          lineHeight: '1.9',
          color: '#374151',
          whiteSpace: 'pre-wrap'
        }}
        dangerouslySetInnerHTML={{ __html: formattedContent }}
      />
    );
  };

  useEffect(() => {
    fetchCompanies();
  }, []);

  const fetchCompanies = async () => {
    try {
      const response = await getCompanies();
      setCompanies(response.data);
      if (response.data.length > 0) {
        setSelectedCompany(response.data[0].id);
      }
    } catch (error) {
      console.error('Error fetching companies:', error);
    }
  };

  const handleGenerate = async () => {
    if (!selectedCompany) return;

    setGenerating(true);
    setError(null);
    setReport(null);

    try {
      const response = await generateFinalReport({
        company_id: selectedCompany,
        report_type: reportType,
        period: period,
        include_ai: includeAI
      });
      setReport(response.data);
    } catch (error) {
      console.error('Error generating report:', error);
      setError('Failed to generate report. Please try again.');
    } finally {
      setGenerating(false);
    }
  };

  const handleDownload = () => {
    if (!report) return;

    const content = `
${report.title}
${'='.repeat(report.title.length)}

Generated: ${new Date().toLocaleString()}
Company: ${report.company_name}
Period: ${report.period}
Report Type: ${report.report_type}

${'-'.repeat(50)}

EXECUTIVE SUMMARY
${'-'.repeat(50)}
${report.executive_summary}

${'-'.repeat(50)}

FINANCIAL HIGHLIGHTS
${'-'.repeat(50)}
${report.sections.map(section => `
${section.title.toUpperCase()}
${section.content}
`).join('\n')}

${report.ai_insights ? `
${'-'.repeat(50)}

AI-POWERED INSIGHTS & RECOMMENDATIONS
${'-'.repeat(50)}
${report.ai_insights}
` : ''}

${'-'.repeat(50)}
Report generated by AI Financial Report Generator
Powered by Claude AI
    `;

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${report.company_name.replace(/\s+/g, '_')}_${report.period.replace(/\s+/g, '_')}_Report.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const reportTypes = [
    { value: 'comprehensive', label: 'Comprehensive Financial Report', description: 'Full analysis including all financial metrics' },
    { value: 'executive', label: 'Executive Summary', description: 'High-level overview for leadership' },
    { value: 'quarterly', label: 'Quarterly Performance', description: 'Quarter-over-quarter analysis' },
    { value: 'compliance', label: 'Compliance Report', description: 'Regulatory compliance status' },
    { value: 'tax', label: 'Tax Summary', description: 'Tax obligations and optimization' },
    { value: 'forecast', label: 'Forecast Report', description: 'Future projections and trends' }
  ];

  const periods = [
    { value: 'Q1 2024', label: 'Q1 2024' },
    { value: 'Q2 2024', label: 'Q2 2024' },
    { value: 'Q3 2024', label: 'Q3 2024' },
    { value: 'Q4 2024', label: 'Q4 2024' },
    { value: 'FY 2024', label: 'Full Year 2024' },
    { value: 'YTD 2024', label: 'Year to Date 2024' }
  ];

  return (
    <div>
      <div style={{ marginBottom: '24px' }}>
        <h1 style={{ fontSize: '24px', fontWeight: '600', color: '#1e293b', marginBottom: '8px' }}>
          Generate Final Report
        </h1>
        <p style={{ color: '#64748b', fontSize: '14px' }}>
          Create comprehensive financial reports with AI-powered insights ready for submission
        </p>
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: '400px 1fr', gap: '24px' }}>
        {/* Configuration Panel */}
        <div className="card" style={{ height: 'fit-content' }}>
          <div className="card-header" style={{ borderBottom: '1px solid #e2e8f0' }}>
            <h3 className="card-title" style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
              <FileText size={20} />
              Report Configuration
            </h3>
          </div>
          <div style={{ padding: '20px', display: 'flex', flexDirection: 'column', gap: '20px' }}>
            {/* Company Selection */}
            <div>
              <label style={{ display: 'flex', alignItems: 'center', gap: '8px', fontSize: '14px', fontWeight: '500', color: '#374151', marginBottom: '8px' }}>
                <Building2 size={16} />
                Select Company
              </label>
              <select
                value={selectedCompany}
                onChange={(e) => setSelectedCompany(e.target.value)}
                style={{
                  width: '100%',
                  padding: '10px 12px',
                  border: '1px solid #d1d5db',
                  borderRadius: '8px',
                  fontSize: '14px',
                  backgroundColor: 'white'
                }}
              >
                {companies.map(company => (
                  <option key={company.id} value={company.id}>{company.name}</option>
                ))}
              </select>
            </div>

            {/* Period Selection */}
            <div>
              <label style={{ display: 'flex', alignItems: 'center', gap: '8px', fontSize: '14px', fontWeight: '500', color: '#374151', marginBottom: '8px' }}>
                <Calendar size={16} />
                Report Period
              </label>
              <select
                value={period}
                onChange={(e) => setPeriod(e.target.value)}
                style={{
                  width: '100%',
                  padding: '10px 12px',
                  border: '1px solid #d1d5db',
                  borderRadius: '8px',
                  fontSize: '14px',
                  backgroundColor: 'white'
                }}
              >
                {periods.map(p => (
                  <option key={p.value} value={p.value}>{p.label}</option>
                ))}
              </select>
            </div>

            {/* Report Type */}
            <div>
              <label style={{ fontSize: '14px', fontWeight: '500', color: '#374151', marginBottom: '12px', display: 'block' }}>
                Report Type
              </label>
              <div style={{ display: 'flex', flexDirection: 'column', gap: '8px' }}>
                {reportTypes.map(type => (
                  <label
                    key={type.value}
                    style={{
                      display: 'flex',
                      alignItems: 'flex-start',
                      gap: '12px',
                      padding: '12px',
                      border: reportType === type.value ? '2px solid #6366f1' : '1px solid #e2e8f0',
                      borderRadius: '8px',
                      cursor: 'pointer',
                      background: reportType === type.value ? '#f5f3ff' : 'white',
                      transition: 'all 0.2s ease'
                    }}
                  >
                    <input
                      type="radio"
                      name="reportType"
                      value={type.value}
                      checked={reportType === type.value}
                      onChange={(e) => setReportType(e.target.value)}
                      style={{ marginTop: '2px' }}
                    />
                    <div>
                      <div style={{ fontSize: '14px', fontWeight: '500', color: '#1e293b' }}>{type.label}</div>
                      <div style={{ fontSize: '12px', color: '#64748b' }}>{type.description}</div>
                    </div>
                  </label>
                ))}
              </div>
            </div>

            {/* AI Toggle */}
            <div>
              <label
                style={{
                  display: 'flex',
                  alignItems: 'center',
                  gap: '12px',
                  padding: '16px',
                  background: 'linear-gradient(135deg, #667eea15 0%, #764ba215 100%)',
                  borderRadius: '12px',
                  cursor: 'pointer',
                  border: '1px solid #e0e7ff'
                }}
              >
                <input
                  type="checkbox"
                  checked={includeAI}
                  onChange={(e) => setIncludeAI(e.target.checked)}
                  style={{ width: '18px', height: '18px' }}
                />
                <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                  <Brain size={20} color="#6366f1" />
                  <div>
                    <div style={{ fontSize: '14px', fontWeight: '500', color: '#1e293b' }}>Include AI Analysis</div>
                    <div style={{ fontSize: '12px', color: '#64748b' }}>Add AI-powered insights and recommendations</div>
                  </div>
                </div>
              </label>
            </div>

            {/* Generate Button */}
            <button
              onClick={handleGenerate}
              disabled={generating || !selectedCompany}
              style={{
                width: '100%',
                padding: '14px',
                background: generating ? '#94a3b8' : 'linear-gradient(135deg, #6366f1 0%, #8b5cf6 100%)',
                color: 'white',
                border: 'none',
                borderRadius: '10px',
                fontSize: '15px',
                fontWeight: '600',
                cursor: generating ? 'not-allowed' : 'pointer',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                gap: '8px',
                boxShadow: '0 4px 6px rgba(99, 102, 241, 0.25)'
              }}
            >
              {generating ? (
                <>
                  <Loader size={18} style={{ animation: 'spin 1s linear infinite' }} />
                  Generating Report...
                </>
              ) : (
                <>
                  <FileText size={18} />
                  Generate Report
                </>
              )}
            </button>
          </div>
        </div>

        {/* Report Preview */}
        <div className="card">
          <div className="card-header" style={{ borderBottom: '1px solid #e2e8f0', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
            <h3 className="card-title">Report Preview</h3>
            {report && (
              <button
                onClick={handleDownload}
                className="btn btn-primary"
                style={{ display: 'flex', alignItems: 'center', gap: '6px' }}
              >
                <Download size={16} />
                Download Report
              </button>
            )}
          </div>
          <div style={{ padding: '24px', minHeight: '600px' }}>
            {error && (
              <div style={{
                padding: '16px',
                background: '#fef2f2',
                border: '1px solid #fecaca',
                borderRadius: '8px',
                color: '#dc2626',
                marginBottom: '16px'
              }}>
                {error}
              </div>
            )}

            {!report && !generating && (
              <div style={{
                display: 'flex',
                flexDirection: 'column',
                alignItems: 'center',
                justifyContent: 'center',
                height: '400px',
                color: '#94a3b8'
              }}>
                <FileText size={64} style={{ opacity: 0.3, marginBottom: '16px' }} />
                <p style={{ fontSize: '16px', marginBottom: '8px' }}>No report generated yet</p>
                <p style={{ fontSize: '14px' }}>Configure your report settings and click "Generate Report"</p>
              </div>
            )}

            {generating && (
              <div style={{
                display: 'flex',
                flexDirection: 'column',
                alignItems: 'center',
                justifyContent: 'center',
                height: '400px'
              }}>
                <div style={{
                  width: '60px',
                  height: '60px',
                  border: '4px solid #e2e8f0',
                  borderTopColor: '#6366f1',
                  borderRadius: '50%',
                  animation: 'spin 1s linear infinite',
                  marginBottom: '20px'
                }}></div>
                <p style={{ fontSize: '16px', color: '#475569', marginBottom: '8px' }}>Generating your report...</p>
                <p style={{ fontSize: '14px', color: '#94a3b8' }}>This may take a moment while AI analyzes your data</p>
              </div>
            )}

            {report && (
              <div style={{ maxWidth: '100%' }}>
                {/* Report Header */}
                <div style={{
                  background: 'linear-gradient(135deg, #1e293b 0%, #334155 100%)',
                  color: 'white',
                  padding: '32px',
                  borderRadius: '12px',
                  marginBottom: '24px'
                }}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '8px' }}>
                    <CheckCircle size={20} color="#10b981" />
                    <span style={{ fontSize: '12px', color: '#10b981', fontWeight: '500' }}>REPORT GENERATED</span>
                  </div>
                  <h1 style={{ fontSize: '24px', fontWeight: '600', marginBottom: '8px' }}>{report.title}</h1>
                  <div style={{ display: 'flex', gap: '24px', fontSize: '14px', color: '#94a3b8' }}>
                    <span>{report.company_name}</span>
                    <span>•</span>
                    <span>{report.period}</span>
                    <span>•</span>
                    <span>{new Date().toLocaleDateString()}</span>
                  </div>
                </div>

                {/* Executive Summary */}
                <div style={{
                  background: '#f8fafc',
                  padding: '24px',
                  borderRadius: '12px',
                  marginBottom: '24px',
                  border: '1px solid #e2e8f0'
                }}>
                  <h2 style={{ fontSize: '18px', fontWeight: '600', color: '#1e293b', marginBottom: '16px' }}>
                    Executive Summary
                  </h2>
                  <p style={{ fontSize: '14px', lineHeight: '1.8', color: '#475569', whiteSpace: 'pre-wrap' }}>
                    {report.executive_summary}
                  </p>
                </div>

                {/* Report Sections */}
                {report.sections && report.sections.map((section, idx) => (
                  <div key={idx} style={{
                    background: 'white',
                    padding: '24px',
                    borderRadius: '12px',
                    marginBottom: '16px',
                    border: '1px solid #e2e8f0'
                  }}>
                    <h3 style={{ fontSize: '16px', fontWeight: '600', color: '#1e293b', marginBottom: '16px' }}>
                      {section.title}
                    </h3>
                    <div style={{ fontSize: '14px', lineHeight: '1.8', color: '#475569', whiteSpace: 'pre-wrap' }}>
                      {section.content}
                    </div>
                  </div>
                ))}

                {/* AI Insights */}
                {report.ai_insights && (
                  <div style={{
                    background: 'linear-gradient(135deg, #1e293b 0%, #334155 100%)',
                    padding: '28px',
                    borderRadius: '20px',
                    marginTop: '24px',
                    boxShadow: '0 10px 40px rgba(0,0,0,0.15)'
                  }}>
                    {/* AI Header */}
                    <div style={{
                      display: 'flex',
                      alignItems: 'center',
                      gap: '16px',
                      marginBottom: '24px',
                      paddingBottom: '20px',
                      borderBottom: '1px solid rgba(255,255,255,0.1)'
                    }}>
                      <div style={{
                        background: 'linear-gradient(135deg, #6366f1 0%, #8b5cf6 100%)',
                        padding: '14px',
                        borderRadius: '16px',
                        boxShadow: '0 8px 24px rgba(99, 102, 241, 0.4)'
                      }}>
                        <Brain size={28} color="white" />
                      </div>
                      <div>
                        <h3 style={{
                          fontSize: '20px',
                          fontWeight: '700',
                          color: 'white',
                          margin: 0,
                          marginBottom: '4px'
                        }}>
                          AI-Powered Strategic Analysis
                        </h3>
                        <p style={{
                          fontSize: '13px',
                          color: 'rgba(255,255,255,0.6)',
                          margin: 0
                        }}>
                          Comprehensive insights generated by Claude AI for executive decision-making
                        </p>
                      </div>
                      <div style={{
                        marginLeft: 'auto',
                        background: 'rgba(16, 185, 129, 0.2)',
                        padding: '8px 16px',
                        borderRadius: '20px',
                        display: 'flex',
                        alignItems: 'center',
                        gap: '6px'
                      }}>
                        <Zap size={14} color="#10b981" />
                        <span style={{ color: '#10b981', fontSize: '12px', fontWeight: '600' }}>AI Generated</span>
                      </div>
                    </div>

                    {/* AI Content */}
                    <div style={{
                      background: 'white',
                      borderRadius: '16px',
                      padding: '24px',
                      boxShadow: 'inset 0 2px 4px rgba(0,0,0,0.05)'
                    }}>
                      {renderAiContent(report.ai_insights)}
                    </div>
                  </div>
                )}
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}

export default GenerateReport;
